<?php

return [



    'data_frame' => [
        ['variable_name'=> 'network_operator_id', 'description' => '', 'start' => 0, 'lenght' => 16, 'type' => 'Q', 'factor' => 1],
        ['variable_name'=> 'equipment_id', 'description' => '',        'start' => 16, 'lenght' => 16, 'type' => 'Q', 'factor' => 1],
        ['variable_name'=> 'latitude', 'description' => '',            'start' => 32, 'lenght' => 8, 'type' => 'f', 'factor' => 1],
        ['variable_name'=> 'longitude', 'description' => '',           'start' => 40, 'lenght' => 8, 'type' => 'f', 'factor' => 1],
        ['variable_name'=> 'flags', 'description' => '',               'start' => 48, 'lenght' => 16, 'type' => 'Q', 'factor' => 1],
        ['variable_name'=> 'timestamp', 'description' => '',           'start' => 64, 'lenght' => 8, 'type' => 'l', 'factor' => 1],
        ['variable_name'=> 'temperature', 'description' => '',         'start' => 72, 'lenght' => 8, 'type' => 'f', 'factor' => 1],
        ['variable_name'=> 'humidity', 'description' => '',            'start' => 80, 'lenght' => 8, 'type' => 'f', 'factor' => 1],
        ['variable_name'=> 'adc0', 'description' => '',                'start' => 88, 'lenght' => 8, 'type' => 'f', 'factor' => 1],
        ['variable_name'=> 'adc1', 'description' => '',                'start' => 96, 'lenght' => 8, 'type' => 'f', 'factor' => 1],
        ['variable_name'=> 'ph1_volt', 'description' => '',            'start' => 104, 'lenght' => 8, 'type' => 'f', 'factor' => 1],
        ['variable_name'=> 'ph2_volt', 'description' => '',            'start' => 112, 'lenght' => 8, 'type' => 'f', 'factor' => 1],
        ['variable_name'=> 'ph3_volt', 'description' => '',            'start' => 120, 'lenght' => 8, 'type' => 'f', 'factor' => 1],
        ['variable_name'=> 'ph1_current', 'description' => '',         'start' => 128, 'lenght' => 8, 'type' => 'f', 'factor' => 1],
        ['variable_name'=> 'ph2_current', 'description' => '',         'start' => 136, 'lenght' => 8, 'type' => 'f', 'factor' => 1],
        ['variable_name'=> 'ph3_current', 'description' => '',         'start' => 144, 'lenght' => 8, 'type' => 'f', 'factor' => 1],
        ['variable_name'=> 'ph1_power', 'description' => '',           'start' => 152, 'lenght' => 8, 'type' => 'f', 'factor' => 1],
        ['variable_name'=> 'ph2_power', 'description' => '',           'start' => 160, 'lenght' => 8, 'type' => 'f', 'factor' => 1],
        ['variable_name'=> 'ph3_power', 'description' => '',           'start' => 168, 'lenght' => 8, 'type' => 'f', 'factor' => 1],
        ['variable_name'=> 'ph1_VA', 'description' => '',              'start' => 176, 'lenght' => 8, 'type' => 'f', 'factor' => 1],
        ['variable_name'=> 'ph2_VA', 'description' => '',              'start' => 184, 'lenght' => 8, 'type' => 'f', 'factor' => 1],
        ['variable_name'=> 'ph3_VA', 'description' => '',              'start' => 192, 'lenght' => 8, 'type' => 'f', 'factor' => 1],
        ['variable_name'=> 'ph1_VAr', 'description' => '',             'start' => 200, 'lenght' => 8, 'type' => 'f', 'factor' => 1],
        ['variable_name'=> 'ph2_VAr', 'description' => '',             'start' => 208, 'lenght' => 8, 'type' => 'f', 'factor' => 1],
        ['variable_name'=> 'ph3_VAr', 'description' => '',             'start' => 216, 'lenght' => 8, 'type' => 'f', 'factor' => 1],
        ['variable_name'=> 'ph1_power_factor', 'description' => '',    'start' => 224, 'lenght' => 8, 'type' => 'f', 'factor' => 1],
        ['variable_name'=> 'ph2_power_factor', 'description' => '',    'start' => 232, 'lenght' => 8, 'type' => 'f', 'factor' => 1],
        ['variable_name'=> 'ph3_power_factor', 'description' => '',    'start' => 240, 'lenght' => 8, 'type' => 'f', 'factor' => 1],
        ['variable_name'=> 'frequency', 'description' => '',           'start' => 248, 'lenght' => 8, 'type' => 'f', 'factor' => 1],
        ['variable_name'=> 'import_wh', 'description' => '',           'start' => 256, 'lenght' => 8, 'type' => 'f', 'factor' => 1],
        ['variable_name'=> 'export_wh', 'description' => '',           'start' => 264, 'lenght' => 8, 'type' => 'f', 'factor' => 1],
        ['variable_name'=> 'import_VArh', 'description' => '',         'start' => 272, 'lenght' => 8, 'type' => 'f', 'factor' => 1],
        ['variable_name'=> 'export_VArh', 'description' => '',         'start' => 280, 'lenght' => 8, 'type' => 'f', 'factor' => 1],
        ['variable_name'=> 'VAh_last_reset', 'description' => '',      'start' => 288, 'lenght' => 8, 'type' => 'f', 'factor' => 1],
        ['variable_name'=> 'Ah_last_reset', 'description' => '',       'start' => 296, 'lenght' => 8, 'type' => 'f', 'factor' => 1],
        ['variable_name'=> 'ph1_ph2_volt', 'description' => '',        'start' => 304, 'lenght' => 8, 'type' => 'f', 'factor' => 1],
        ['variable_name'=> 'ph2_ph3_volt', 'description' => '',        'start' => 312, 'lenght' => 8, 'type' => 'f', 'factor' => 1],
        ['variable_name'=> 'ph3_ph1_volt', 'description' => '',        'start' => 320, 'lenght' => 8, 'type' => 'f', 'factor' => 1],
        ['variable_name'=> 'ph1_volt_thd', 'description' => '',        'start' => 328, 'lenght' => 8, 'type' => 'f', 'factor' => 1],
        ['variable_name'=> 'ph2_volt_thd', 'description' => '',        'start' => 336, 'lenght' => 8, 'type' => 'f', 'factor' => 1],
        ['variable_name'=> 'ph3_volt_thd', 'description' => '',        'start' => 344, 'lenght' => 8, 'type' => 'f', 'factor' => 1],
        ['variable_name'=> 'ph1_current_thd', 'description' => '',     'start' => 352, 'lenght' => 8, 'type' => 'f', 'factor' => 1],
        ['variable_name'=> 'ph2_current_thd', 'description' => '',     'start' => 360, 'lenght' => 8, 'type' => 'f', 'factor' => 1],
        ['variable_name'=> 'ph3_current_thd', 'description' => '',     'start' => 368, 'lenght' => 8, 'type' => 'f', 'factor' => 1],
        ['variable_name'=> 'ph1_ph2_volt_thd', 'description' => '',    'start' => 376, 'lenght' => 8, 'type' => 'f', 'factor' => 1],
        ['variable_name'=> 'ph2_ph3_volt_thd', 'description' => '',    'start' => 384, 'lenght' => 8, 'type' => 'f', 'factor' => 1],
        ['variable_name'=> 'ph3_ph1_volt_thd', 'description' => '',    'start' => 392, 'lenght' => 8, 'type' => 'f', 'factor' => 1],
    ],
    'flags_frame' => [
        ['flag_name'=> 'flagStorage', 'description' => '',      'bit' => 0, 'index' => 63],
        ['flag_name'=> 'flagRealTime', 'description' => '',     'bit' => 1, 'index' => 62],
        ['flag_name'=> 'flagAlert', 'description' => '',        'bit' => 2, 'index' => 61],
        ['flag_name'=> 'coil1', 'description' => '',            'bit' => 3, 'index' => 60],
        ['flag_name'=> 'coil2', 'description' => '',            'bit' => 4, 'index' => 59],
        ['flag_name'=> 'coil3', 'description' => '',            'bit' => 5, 'index' => 58],
        ['flag_name'=> 'coil4', 'description' => '',            'bit' => 6, 'index' => 57],
        ['flag_name'=> 'coil5', 'description' => '',            'bit' => 7, 'index' => 56],
        ['flag_name'=> 'coil6', 'description' => '',            'bit' => 8, 'index' => 55],
        ['flag_name'=> 'coil7', 'description' => '',            'bit' => 9, 'index' => 54],
        ['flag_name'=> 'coil8', 'description' => '',            'bit' => 10, 'index' => 53],
        ['flag_name'=> 'coil9', 'description' => '',            'bit' => 11, 'index' => 52],
        ['flag_name'=> 'coil10', 'description' => '',           'bit' => 12, 'index' => 51],
        ['flag_name'=> 'real_consumption', 'description' => '', 'bit' => 13, 'index' => 50],
    ['flag_name'=> 'reactive_consumption', 'description' => '', 'bit' => 14, 'index' => 49],

        ['flag_name'=> 'flagOpened', 'description' => '',       'bit' => 27, 'index' => 36],
        ['flag_name'=> 'flagAdc1', 'description' => '',         'bit' => 28, 'index' => 35, 'variable_name' => 'adc1'],
        ['flag_name'=> 'flagVolt1', 'description' => '',        'bit' => 29, 'index' => 34, 'variable_name' => 'ph1_volt'],
        ['flag_name'=> 'flagVolt2', 'description' => '',        'bit' => 30, 'index' => 33, 'variable_name' => 'ph2_volt'],
        ['flag_name'=> 'flagVolt3', 'description' => '',        'bit' => 31, 'index' => 32, 'variable_name' => 'ph3_volt'],
        ['flag_name'=> 'flagCurr1', 'description' => '',        'bit' => 32, 'index' => 31, 'variable_name' => 'ph1_current'],
        ['flag_name'=> 'flagCurr2', 'description' => '',        'bit' => 33, 'index' => 30, 'variable_name' => 'ph2_current'],
        ['flag_name'=> 'flagCurr3', 'description' => '',        'bit' => 34, 'index' => 29, 'variable_name' => 'ph3_current'],
        ['flag_name'=> 'flagPot1', 'description' => '',         'bit' => 35, 'index' => 28, 'variable_name' => 'ph1_power'],
        ['flag_name'=> 'flagPot2', 'description' => '',         'bit' => 36, 'index' => 27, 'variable_name' => 'ph2_power'],
        ['flag_name'=> 'flagPot3', 'description' => '',         'bit' => 37, 'index' => 26, 'variable_name' => 'ph3_power'],
        ['flag_name'=> 'flagVA1', 'description' => '',          'bit' => 38, 'index' => 25, 'variable_name' => 'ph1_VA'],
        ['flag_name'=> 'flagVA2', 'description' => '',          'bit' => 39, 'index' => 24, 'variable_name' => 'ph2_VA'],
        ['flag_name'=> 'flagVA3', 'description' => '',          'bit' => 40, 'index' => 23, 'variable_name' => 'ph3_VA'],
        ['flag_name'=> 'flagVAr1', 'description' => '',         'bit' => 41, 'index' => 22, 'variable_name' => 'ph1_VAr'],
        ['flag_name'=> 'flagVAr2', 'description' => '',         'bit' => 42, 'index' => 21, 'variable_name' => 'ph2_VAr'],
        ['flag_name'=> 'flagVAr3', 'description' => '',         'bit' => 43, 'index' => 20, 'variable_name' => 'ph3_VAr'],
        ['flag_name'=> 'flagPF1', 'description' => '',          'bit' => 44, 'index' => 19, 'variable_name' => 'ph1_power_factor'],
        ['flag_name'=> 'flagPF2', 'description' => '',          'bit' => 45, 'index' => 18, 'variable_name' => 'ph2_power_factor'],
        ['flag_name'=> 'flagPF3', 'description' => '',          'bit' => 46, 'index' => 17, 'variable_name' => 'ph3_power_factor'],
        ['flag_name'=> 'flag_Freq', 'description' => '',        'bit' => 47, 'index' => 16, 'variable_name' => 'frequency'],
        ['flag_name'=> 'flagWhImp', 'description' => '',        'bit' => 48, 'index' => 15, 'variable_name' => 'import_wh'],
        ['flag_name'=> 'flagWhExp', 'description' => '',        'bit' => 49, 'index' => 14, 'variable_name' => 'export_wh'],
        ['flag_name'=> 'flagVArhImp', 'description' => '',      'bit' => 50, 'index' => 13, 'variable_name' => 'import_VArh'],
        ['flag_name'=> 'flagVArhExp', 'description' => '',      'bit' => 51, 'index' => 12, 'variable_name' => 'import_VArh'],
        ['flag_name'=> 'flagVolt12', 'description' => '',       'bit' => 52, 'index' => 11, 'variable_name' => 'ph1_ph2_volt'],
        ['flag_name'=> 'flagVolt23', 'description' => '',       'bit' => 53, 'index' => 10, 'variable_name' => 'ph2_ph3_volt'],
        ['flag_name'=> 'flagVolt31', 'description' => '',       'bit' => 54, 'index' => 9,  'variable_name' => 'ph3_ph1_volt'],
        ['flag_name'=> 'flagTHDVolt1', 'description' => '',     'bit' => 55, 'index' => 8,  'variable_name' => 'ph1_volt_thd'],
        ['flag_name'=> 'flagTHDVolt2', 'description' => '',     'bit' => 56, 'index' => 7,  'variable_name' => 'ph2_volt_thd'],
        ['flag_name'=> 'flagTHDVolt3', 'description' => '',     'bit' => 57, 'index' => 6,  'variable_name' => 'ph3_volt_thd'],
        ['flag_name'=> 'flagTHDCurr1', 'description' => '',     'bit' => 58, 'index' => 5,  'variable_name' => 'ph1_current_thd'],
        ['flag_name'=> 'flagTHDCurr2', 'description' => '',     'bit' => 59, 'index' => 4,  'variable_name' => 'ph2_current_thd'],
        ['flag_name'=> 'flagTHDCurr3', 'description' => '',     'bit' => 60, 'index' => 3,  'variable_name' => 'ph3_current_thd'],
        ['flag_name'=> 'flagTHDVolt12', 'description' => '',    'bit' => 61, 'index' => 2,  'variable_name' => 'ph1_ph2_volt_thd'],
        ['flag_name'=> 'flagTHDVolt23', 'description' => '',    'bit' => 62, 'index' => 1,  'variable_name' => 'ph2_ph3_volt_thd'],
        ['flag_name'=> 'flagTHDVolt31', 'description' => '',    'bit' => 63, 'index' => 0,  'variable_name' => 'ph3_ph1_volt_thd'],
        ]

];
