<?php

return [
    'variables' => [
        ['id' => 1,  'display_name' =>  'Energia activa(kWh)',         'icon'=>'fas fa-tachometer-alt',                  'variable_name'=> 'import_wh',          'chart_type' => 'line',   'style' => 'active_energy'],
        ['id' => 2,  'display_name' =>  'Horario(kWh)',                'icon'=>'fas fa-tachometer-alt',                  'variable_name'=> 'import_wh',          'chart_type' => 'column', 'style' => 'active_energy'],
        ['id' => 3,  'display_name' =>  'Acumulado fases(kWh)',        'icon'=>'fas fa-tachometer-alt',                  'variable_name'=> 'phase_import_kwh',   'chart_type' => 'line',   'style' => 'active_energy'],
        ['id' => 4,  'display_name' =>  'Horario fases(kWh)',        'icon'=>'fas fa-tachometer-alt',                  'variable_name'=> 'phase_import_kwh',   'chart_type' => 'column',   'style' => 'active_energy'],

        ['id' => 5,  'display_name' =>  'Energia reactiva(kVARh)',     'icon'=>'fas fa-atom',                            'variable_name'=> 'import_VArh',        'chart_type' => 'line',   'style' => 'reactive_energy'],
        ['id' => 6,  'display_name' =>  'Horario(kVARh)',              'icon'=>'fas fa-atom',                            'variable_name'=> 'import_wh',          'chart_type' => 'column', 'style' => 'reactive_energy'],
        ['id' => 7,  'display_name' =>  'Acumulado fases (kVARh)',     'icon'=>'fas fa-atom',                            'variable_name'=> 'phase_import_kvarh', 'chart_type' => 'line',   'style' => 'reactive_energy'],
        ['id' => 8,  'display_name' =>  'Horario fases (kVARh)',     'icon'=>'fas fa-atom',                            'variable_name'=> 'phase_import_kvarh', 'chart_type' => 'column',   'style' => 'reactive_energy'],

        ['id' => 9,  'display_name' =>  'Reactiva Capacitiva(kVARCh)', 'icon'=>"fa-brands fa-creative-commons-nd",       'variable_name'=> 'phase_import_kvarh', 'chart_type' => 'line',   'style' => 'reactive_capacitive'],
        ['id' => 10,  'display_name' => 'Horario (kVARCh)',             'icon'=>'fa-brands fa-creative-commons-nd',       'variable_name'=> 'import_VArh',        'chart_type' => 'column', 'style' => 'reactive_capacitive'],
        ['id' => 11,  'display_name' =>  'Acumulado fases (kVARCh)',    'icon'=>'fa-brands fa-creative-commons-nd',       'variable_name'=> 'import_VArh',        'chart_type' => 'line',   'style' => 'reactive_capacitive'],
        ['id' => 12, 'display_name' =>  'Horario fases (kVARCh)',      'icon'=>'fa-brands fa-creative-commons-nd',       'variable_name'=> 'import_VArh',        'chart_type' => 'column', 'style' => 'reactive_capacitive'],

        ['id' => 13, 'display_name' =>  'Reactiva Inductiva(kVARLh)',  'icon'=>"fa-brands fa-creative-commons-sampling", 'variable_name'=> 'phase_import_kvarh', 'chart_type' => 'line',   'style' => 'reactive_inductive'],
        ['id' => 14, 'display_name' => 'Horario (kVARLh)',             'icon'=>'fa-brands fa-creative-commons-sampling', 'variable_name'=> 'import_VArh',        'chart_type' => 'column', 'style' => 'reactive_inductive'],
        ['id' => 15, 'display_name' => 'Acumulado fases (kVARLh)',     'icon'=>'fa-brands fa-creative-commons-sampling', 'variable_name'=> 'import_VArh',        'chart_type' => 'line',   'style' => 'reactive_inductive'],
        ['id' => 16, 'display_name' => 'Horario fases (kVARLh)',       'icon'=>'fa-brands fa-creative-commons-sampling', 'variable_name'=> 'import_VArh',        'chart_type' => 'column', 'style' => 'reactive_inductive'],


        ['id' => 17, 'display_name' =>  'Voltaje(V)',                  'icon'=>'fas fa-lightbulb',                       'variable_name'=> 'volt',               'chart_type' => 'line',   'style' => 'voltage'],
        ['id' => 18, 'display_name' =>  'Corriente(A)',                'icon'=>'fas fa-bolt',                            'variable_name'=> 'current',            'chart_type' => 'line',   'style' => 'current'],
        ['id' => 19, 'display_name' =>  'Potencia(W)',                 'icon'=>'fas fa-long-arrow-alt-right',            'variable_name'=> 'power',              'chart_type' => 'line',   'style' => 'power'],
        ['id' => 20, 'display_name' =>  'P. Aparente(VA)',             'icon'=>'fas fa-expand-alt',                      'variable_name'=> 'VA',                 'chart_type' => 'line',   'style' => 'power'],
        ['id' => 21, 'display_name' =>  'P. Reactiva(VAR)',            'icon'=>'fas fa-long-arrow-alt-up',               'variable_name'=> 'VAr',                'chart_type' => 'line',   'style' => 'power'],
        ['id' => 22, 'display_name' =>  'FP',                          'icon'=>'fas fa-exchange-alt',                    'variable_name'=> 'power_factor',       'chart_type' => 'line',   'style' => 'power_factor'],
        ['id' => 23, 'display_name' =>  'Angulo fase',                 'icon'=>'fas fa-greater-than-equal',              'variable_name'=> 'phase_angle',        'chart_type' => 'line',   'style' => 'phase_angle'],
        ['id' => 24, 'display_name' =>  'Voltaje fases(V)',            'icon'=>'fas fa-code-branch',                     'variable_name'=> 'volts',              'chart_type' => 'line',   'style' =>  'voltage'],
        ['id' => 25, 'display_name' =>  'THDI(%)',                     'icon'=>'fas fa-hubspot',                         'variable_name'=> 'current_thd',        'chart_type' => 'line',   'style' => 'thd'],
        ['id' => 26, 'display_name' =>  'THDV(%)',                     'icon'=>'fas fa-percentage',                      'variable_name'=> 'volt_thd',           'chart_type' => 'line',   'style' => 'thd'],
        ['id' => 27, 'display_name' =>  'THDV fases(%)',               'icon'=>'fas fa-percent',                         'variable_name'=> 'volts_thd',          'chart_type' => 'line',   'style' => 'thd'],
        ['id' => 28, 'display_name' =>  'Frecuencia(Hz)',              'icon'=>'fas fa-chart-line',                      'variable_name'=> 'frecuency' ,         'chart_type' => 'line',   'style' => 'frecuency'],
    ],


    'data_frame' => [
        ['variable_name'=> 'network_operator_id', 'description' => '', 'display_name' => '',    'variable_id'=> '', 'key' => '',          'start' => 0,   'lenght' => 16, 'type' => 'Q', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'equipment_id', 'description' => '',        'display_name' => '',    'variable_id'=> '', 'key' => '',          'start' => 16,  'lenght' => 16, 'type' => 'Q', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'latitude', 'description' => '',            'display_name' => '',    'variable_id'=> '', 'key' => '',          'start' => 32,  'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'longitude', 'description' => '',           'display_name' => '',    'variable_id'=> '', 'key' => '',          'start' => 40,  'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'flags', 'description' => '',               'display_name' => '',    'variable_id'=> '', 'key' => '',          'start' => 48,  'lenght' => 16, 'type' => 'Q', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'timestamp', 'description' => '',           'display_name' => '',    'variable_id'=> '', 'key' => '',          'start' => 64,  'lenght' => 8,  'type' => 'l', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'ph1_volt', 'description' => '',            'display_name' => 'L1 V',    'variable_id'=> 17, 'key' => 'L1',        'start' => 72,  'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'ph2_volt', 'description' => '',            'display_name' => 'L2 V',    'variable_id'=> 17, 'key' => 'L2',        'start' => 80,  'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'ph3_volt', 'description' => '',            'display_name' => 'L3 V',    'variable_id'=> 17, 'key' => 'L3',        'start' => 88,  'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'ph1_current', 'description' => '',         'display_name' => 'L1 A',    'variable_id'=> 18, 'key' => 'L1',        'start' => 96,  'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'ph2_current', 'description' => '',         'display_name' => 'L2 A',    'variable_id'=> 18, 'key' => 'L2',        'start' => 104, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'ph3_current', 'description' => '',         'display_name' => 'L3 A',    'variable_id'=> 18, 'key' => 'L3',        'start' => 112, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'ph1_power', 'description' => '',           'display_name' => 'L1 W',    'variable_id'=> 19, 'key' => 'L1',        'start' => 120, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'ph2_power', 'description' => '',           'display_name' => 'L2 W',    'variable_id'=> 19, 'key' => 'L2',        'start' => 128, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'ph3_power', 'description' => '',           'display_name' => 'L3 W',    'variable_id'=> 19, 'key' => 'L3',        'start' => 136, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'ph1_VA', 'description' => '',              'display_name' => 'L1 VA',    'variable_id'=> 20, 'key' => 'L1',        'start' => 144, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'ph2_VA', 'description' => '',              'display_name' => 'L2 VA',    'variable_id'=> 20, 'key' => 'L2',        'start' => 152, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'ph3_VA', 'description' => '',              'display_name' => 'L3 VA',    'variable_id'=> 20, 'key' => 'L3',        'start' => 160, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'ph1_VAr', 'description' => '',             'display_name' => 'L1 VAR',    'variable_id'=> 21, 'key' => 'L1',        'start' => 168, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'ph2_VAr', 'description' => '',             'display_name' => 'l2 VAR',    'variable_id'=> 21, 'key' => 'L2',        'start' => 176, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'ph3_VAr', 'description' => '',             'display_name' => 'L3 VAR',    'variable_id'=> 21, 'key' => 'L3',        'start' => 184, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'ph1_power_factor', 'description' => '',    'display_name' => 'L1 FP',    'variable_id'=> 22, 'key' => 'L1',        'start' => 192, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'ph2_power_factor', 'description' => '',    'display_name' => 'L2 FP',    'variable_id'=> 22, 'key' => 'L2',        'start' => 200, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'ph3_power_factor', 'description' => '',    'display_name' => 'L3 FP',    'variable_id'=> 22, 'key' => 'L3',        'start' => 208, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'ph1_phase_angle', 'description' => '',     'display_name' => 'L1 AF',    'variable_id'=> 23, 'key' => 'L1',        'start' => 216, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'ph2_phase_angle', 'description' => '',     'display_name' => 'L2 AF',    'variable_id'=> 23, 'key' => 'L2',        'start' => 224, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'ph3_phase_angle', 'description' => '',     'display_name' => 'L3 AF',    'variable_id'=> 23, 'key' => 'L3',        'start' => 232, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'total_system_power', 'description' => '',  'display_name' => '',    'variable_id'=> '', 'key' => '',          'start' => 240, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'total_system_var', 'description' => '',    'display_name' => '',    'variable_id'=> '', 'key' => '',          'start' => 248, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'frequency', 'description' => '',           'display_name' => 'FRECUECNIA',    'variable_id'=> 28, 'key' => 'Hz',        'start' => 256, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'import_wh', 'description' => '',           'display_name' => 'ENERGIA kWh TOTAL',    'variable_id'=> 1,  'key' => 'TOTAL',     'start' => 264, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'export_wh', 'description' => '',           'display_name' => '',    'variable_id'=> '', 'key' => '',          'start' => 272, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'import_VArh', 'description' => '',         'display_name' => 'ENERGIA kVARh TOTAL',    'variable_id'=> 5,  'key' => 'TOTAL',     'start' => 280, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'export_VArh', 'description' => '',         'display_name' => '',    'variable_id'=> '', 'key' => '',          'start' => 288, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'ph1_ph2_volt', 'description' => '',        'display_name' => 'L1-L2 V',    'variable_id'=> 24, 'key' => 'L1-L2',     'start' => 296, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'ph2_ph3_volt', 'description' => '',        'display_name' => 'L2-L3 V',    'variable_id'=> 24, 'key' => 'L2-L3',     'start' => 304, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'ph3_ph1_volt', 'description' => '',        'display_name' => 'L3-L4 V',    'variable_id'=> 24, 'key' => 'L3-L1',     'start' => 312, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'ph1_volt_thd', 'description' => '',        'display_name' => 'L1 VTHD',    'variable_id'=> 26, 'key' => 'L1',        'start' => 320, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'ph2_volt_thd', 'description' => '',        'display_name' => 'L2 VTHD',    'variable_id'=> 26, 'key' => 'L2',        'start' => 328, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'ph3_volt_thd', 'description' => '',        'display_name' => 'L3 VTHD',    'variable_id'=> 26, 'key' => 'L3',        'start' => 336, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'ph1_current_thd', 'description' => '',     'display_name' => 'L1 ATHD',    'variable_id'=> 25, 'key' => 'L1',        'start' => 344, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'ph2_current_thd', 'description' => '',     'display_name' => 'L2 ATHD',    'variable_id'=> 25, 'key' => 'L2',        'start' => 352, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'ph3_current_thd', 'description' => '',     'display_name' => 'L3 ATHD',    'variable_id'=> 25, 'key' => 'L3',        'start' => 360, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'ph1_ph2_volt_thd', 'description' => '',    'display_name' => 'L1-L2 VTHD',    'variable_id'=> 27, 'key' => 'L1-L2',     'start' => 368, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'ph2_ph3_volt_thd', 'description' => '',    'display_name' => 'L2-L3 VTHD',    'variable_id'=> 27, 'key' => 'L2-L3',     'start' => 376, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'ph3_ph1_volt_thd', 'description' => '',    'display_name' => 'L3-L1 VTHD',    'variable_id'=> 27, 'key' => 'L3-L1',     'start' => 384, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'ph1_import_kwh', 'description' => '',      'display_name' => 'L1 ENERGIA kWh TOTAL',    'variable_id'=> 3,  'key' => 'L1',        'start' => 392, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'ph2_import_kwh', 'description' => '',      'display_name' => 'L2 ENERGIA kWh TOTAL',    'variable_id'=> 3,  'key' => 'L2',        'start' => 400, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'ph3_import_kwh', 'description' => '',      'display_name' => 'L3 ENERGIA kWh TOTAL',    'variable_id'=> 3,  'key' => 'L3',        'start' => 408, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'ph1_import_kvarh', 'description' => '',    'display_name' => 'L1 ENERGIA kVARh TOTAL',    'variable_id'=> 7,  'key' => 'L1',        'start' => 416, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'ph2_import_kvarh', 'description' => '',    'display_name' => 'L2 ENERGIA kVARh TOTAL',    'variable_id'=> 7,  'key' => 'L2',        'start' => 424, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'ph3_import_kvarh', 'description' => '',    'display_name' => 'L3 ENERGIA kVARh TOTAL',    'variable_id'=> 7,  'key' => 'L3',        'start' => 432, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'ph1_varCh_acumm', 'description' => '',     'display_name' => 'L1 ENERGIA kVARCh TOTAL',    'variable_id'=> 11,  'key' => 'L1',       'start' => 440, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'ph1_varLh_acumm', 'description' => '',     'display_name' => 'L1 ENERGIA kVARLh TOTAL',    'variable_id'=> 15, 'key' => 'L1',        'start' => 448, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'ph2_varCh_acumm', 'description' => '',     'display_name' => 'L2 ENERGIA kVARCh TOTAL',    'variable_id'=> 11,  'key' => 'L2',       'start' => 456, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'ph2_varLh_acumm', 'description' => '',     'display_name' => 'L2 ENERGIA kVARLh TOTAL',    'variable_id'=> 15, 'key' => 'L2',        'start' => 464, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'ph3_varCh_acumm', 'description' => '',     'display_name' => 'L3 ENERGIA kVARCh TOTAL',    'variable_id'=> 11,  'key' => 'L3',       'start' => 472, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'ph3_varLh_acumm', 'description' => '',     'display_name' => 'L3 ENERGIA kVARLh TOTAL',    'variable_id'=> 15, 'key' => 'L3',        'start' => 480, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'Wh_calc', 'description' => '',             'display_name' => '',    'variable_id'=> '', 'key' => '',          'start' => 488, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'ph1_varCh_interval', 'description' => '',  'display_name' => 'L1 ENERGIA kVARCh HORARIO',    'variable_id'=> 12, 'key' => 'L1',        'start' => 496, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => true],
        ['variable_name'=> 'ph1_varLh_interval', 'description' => '',  'display_name' => 'L1 ENERGIA kVARLh HORARIO',    'variable_id'=> 16, 'key' => 'L1',        'start' => 504, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => true],
        ['variable_name'=> 'ph2_varCh_interval', 'description' => '',  'display_name' => 'L2 ENERGIA kVARCh HORARIO',    'variable_id'=> 12, 'key' => 'L2',        'start' => 512, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => true],
        ['variable_name'=> 'ph2_varLh_interval', 'description' => '',  'display_name' => 'L2 ENERGIA kVARLh HORARIO',    'variable_id'=> 16, 'key' => 'L2',        'start' => 520, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => true],
        ['variable_name'=> 'ph3_varCh_interval', 'description' => '',  'display_name' => 'L3 ENERGIA kVARCh HORARIO',    'variable_id'=> 12, 'key' => 'L3',        'start' => 528, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => true],
        ['variable_name'=> 'ph3_varLh_interval', 'description' => '',  'display_name' => 'L3 ENERGIA kVARLh HORARIO',    'variable_id'=> 16, 'key' => 'L3',        'start' => 536, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => true],
        ['variable_name'=> 'varLh_acumm', 'description' => '',         'display_name' => 'ENERGIA kVARLh TOTAL',    'variable_id'=> 13, 'key' => 'TOTAL',     'start' => 544, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'varCh_acumm', 'description' => '',         'display_name' => 'ENERGIA kVARCh TOTAL',    'variable_id'=> 9,  'key' => 'TOTAL',     'start' => 552, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['variable_name'=> 'kwh_interval', 'description' => '',        'display_name' => 'ENERGIA kWh HORARIO',    'variable_id'=> 2,  'key' => 'TOTAL',     'start' => 568, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => true],
        ['variable_name'=> 'varLh_interval', 'description' => '',      'display_name' => 'ENERGIA kVARLh HORARIO',    'variable_id'=> 14, 'key' => 'TOTAL',     'start' => 560, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => true],
        ['variable_name'=> 'varCh_interval', 'description' => '',      'display_name' => 'ENERGIA kVARCh HORARIO',    'variable_id'=> 10,  'key' => 'TOTAL',    'start' => 568, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => true],
        ['variable_name'=> 'ph1_kwh_interval', 'description' => '',    'display_name' => 'L1 ENERGIA kWh HORARIO',    'variable_id'=> 4,  'key' => 'L1',        'start' => 568, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => true],
        ['variable_name'=> 'ph2_kwh_interval', 'description' => '',    'display_name' => 'L2 ENERGIA kWh HORARIO',    'variable_id'=> 4,  'key' => 'L2',        'start' => 568, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => true],
        ['variable_name'=> 'ph3_kwh_interval', 'description' => '',    'display_name' => 'L3 ENERGIA kWh HORARIO',    'variable_id'=> 4,  'key' => 'L3',        'start' => 568, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => true],
        ['variable_name'=> 'varh_interval', 'description' => '',       'display_name' => 'ENERGIA kVARh HORARIO',    'variable_id'=> 6,  'key' => 'TOTAL',     'start' => 568, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => true],
        ['variable_name'=> 'ph1_varh_interval', 'description' => '',   'display_name' => 'L1 ENERGIA kVARh HORARIO',    'variable_id'=> 8,  'key' => 'L1',        'start' => 568, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => true],
        ['variable_name'=> 'ph2_varh_interval', 'description' => '',   'display_name' => 'L2 ENERGIA kVARh HORARIO',    'variable_id'=> 8,  'key' => 'L2',        'start' => 568, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => true],
        ['variable_name'=> 'ph3_varh_interval', 'description' => '',   'display_name' => 'L3 ENERGIA kVARh HORARIO',    'variable_id'=> 8,  'key' => 'L3',        'start' => 568, 'lenght' => 8,  'type' => 'f', 'factor' => 1, 'bolean_accum' => true],
    ],

    'flags_frame' => [
        ['flag_name'=> 'flagStorage', 'description' => '',      'bit' => 0, 'index' => 63],
        ['flag_name'=> 'flagRealTime', 'description' => '',     'bit' => 1, 'index' => 62],
        ['flag_name'=> 'flagAlert', 'description' => '',        'bit' => 2, 'index' => 61],
        ['flag_name'=> 'coil1', 'description' => '',            'bit' => 3, 'index' => 60],
        ['flag_name'=> 'coil2', 'description' => '',            'bit' => 4, 'index' => 59],
        ['flag_name'=> 'coil3', 'description' => '',            'bit' => 5, 'index' => 58],
        ['flag_name'=> 'coil4', 'description' => '',            'bit' => 6, 'index' => 57],
        ['flag_name'=> 'coil5', 'description' => '',            'bit' => 7, 'index' => 56],
        ['flag_name'=> 'coil6', 'description' => '',            'bit' => 8, 'index' => 55],
        ['flag_name'=> 'coil7', 'description' => '',            'bit' => 9, 'index' => 54],
        ['flag_name'=> 'coil8', 'description' => '',            'bit' => 10, 'index' => 53],
        ['flag_name'=> 'coil9', 'description' => '',            'bit' => 11, 'index' => 52],
        ['flag_name'=> 'coil10', 'description' => '',           'bit' => 12, 'index' => 51],
        ['flag_name'=> 'real_consumption', 'description' => '', 'bit' => 13, 'index' => 50],
    ['flag_name'=> 'reactive_consumption', 'description' => '', 'bit' => 14, 'index' => 49],

        ['flag_name'=> 'flagOpened', 'description' => '',       'bit' => 27, 'index' => 36],
        ['flag_name'=> 'flagAdc1', 'description' => '',         'bit' => 28, 'index' => 35, 'variable_name' => 'adc1'],
        ['flag_name'=> 'flagVolt1', 'description' => '',        'bit' => 29, 'index' => 34, 'variable_name' => 'ph1_volt'],
        ['flag_name'=> 'flagVolt2', 'description' => '',        'bit' => 30, 'index' => 33, 'variable_name' => 'ph2_volt'],
        ['flag_name'=> 'flagVolt3', 'description' => '',        'bit' => 31, 'index' => 32, 'variable_name' => 'ph3_volt'],
        ['flag_name'=> 'flagCurr1', 'description' => '',        'bit' => 32, 'index' => 31, 'variable_name' => 'ph1_current'],
        ['flag_name'=> 'flagCurr2', 'description' => '',        'bit' => 33, 'index' => 30, 'variable_name' => 'ph2_current'],
        ['flag_name'=> 'flagCurr3', 'description' => '',        'bit' => 34, 'index' => 29, 'variable_name' => 'ph3_current'],
        ['flag_name'=> 'flagPot1', 'description' => '',         'bit' => 35, 'index' => 28, 'variable_name' => 'ph1_power'],
        ['flag_name'=> 'flagPot2', 'description' => '',         'bit' => 36, 'index' => 27, 'variable_name' => 'ph2_power'],
        ['flag_name'=> 'flagPot3', 'description' => '',         'bit' => 37, 'index' => 26, 'variable_name' => 'ph3_power'],
        ['flag_name'=> 'flagVA1', 'description' => '',          'bit' => 38, 'index' => 25, 'variable_name' => 'ph1_VA'],
        ['flag_name'=> 'flagVA2', 'description' => '',          'bit' => 39, 'index' => 24, 'variable_name' => 'ph2_VA'],
        ['flag_name'=> 'flagVA3', 'description' => '',          'bit' => 40, 'index' => 23, 'variable_name' => 'ph3_VA'],
        ['flag_name'=> 'flagVAr1', 'description' => '',         'bit' => 41, 'index' => 22, 'variable_name' => 'ph1_VAr'],
        ['flag_name'=> 'flagVAr2', 'description' => '',         'bit' => 42, 'index' => 21, 'variable_name' => 'ph2_VAr'],
        ['flag_name'=> 'flagVAr3', 'description' => '',         'bit' => 43, 'index' => 20, 'variable_name' => 'ph3_VAr'],
        ['flag_name'=> 'flagPF1', 'description' => '',          'bit' => 44, 'index' => 19, 'variable_name' => 'ph1_power_factor'],
        ['flag_name'=> 'flagPF2', 'description' => '',          'bit' => 45, 'index' => 18, 'variable_name' => 'ph2_power_factor'],
        ['flag_name'=> 'flagPF3', 'description' => '',          'bit' => 46, 'index' => 17, 'variable_name' => 'ph3_power_factor'],
        ['flag_name'=> 'flag_Freq', 'description' => '',        'bit' => 47, 'index' => 16, 'variable_name' => 'frequency'],
        ['flag_name'=> 'flagWhImp', 'description' => '',        'bit' => 48, 'index' => 15, 'variable_name' => 'import_wh'],
        ['flag_name'=> 'flagWhExp', 'description' => '',        'bit' => 49, 'index' => 14, 'variable_name' => 'export_wh'],
        ['flag_name'=> 'flagVArhImp', 'description' => '',      'bit' => 50, 'index' => 13, 'variable_name' => 'import_VArh'],
        ['flag_name'=> 'flagVArhExp', 'description' => '',      'bit' => 51, 'index' => 12, 'variable_name' => 'import_VArh'],
        ['flag_name'=> 'flagVolt12', 'description' => '',       'bit' => 52, 'index' => 11, 'variable_name' => 'ph1_ph2_volt'],
        ['flag_name'=> 'flagVolt23', 'description' => '',       'bit' => 53, 'index' => 10, 'variable_name' => 'ph2_ph3_volt'],
        ['flag_name'=> 'flagVolt31', 'description' => '',       'bit' => 54, 'index' => 9,  'variable_name' => 'ph3_ph1_volt'],
        ['flag_name'=> 'flagTHDVolt1', 'description' => '',     'bit' => 55, 'index' => 8,  'variable_name' => 'ph1_volt_thd'],
        ['flag_name'=> 'flagTHDVolt2', 'description' => '',     'bit' => 56, 'index' => 7,  'variable_name' => 'ph2_volt_thd'],
        ['flag_name'=> 'flagTHDVolt3', 'description' => '',     'bit' => 57, 'index' => 6,  'variable_name' => 'ph3_volt_thd'],
        ['flag_name'=> 'flagTHDCurr1', 'description' => '',     'bit' => 58, 'index' => 5,  'variable_name' => 'ph1_current_thd'],
        ['flag_name'=> 'flagTHDCurr2', 'description' => '',     'bit' => 59, 'index' => 4,  'variable_name' => 'ph2_current_thd'],
        ['flag_name'=> 'flagTHDCurr3', 'description' => '',     'bit' => 60, 'index' => 3,  'variable_name' => 'ph3_current_thd'],
        ['flag_name'=> 'flagTHDVolt12', 'description' => '',    'bit' => 61, 'index' => 2,  'variable_name' => 'ph1_ph2_volt_thd'],
        ['flag_name'=> 'flagTHDVolt23', 'description' => '',    'bit' => 62, 'index' => 1,  'variable_name' => 'ph2_ph3_volt_thd'],
        ['flag_name'=> 'flagTHDVolt31', 'description' => '',    'bit' => 63, 'index' => 0,  'variable_name' => 'ph3_ph1_volt_thd'],
        ]

];
